kind: Pod
apiVersion: v1
metadata:
  name: secret-test-pod
  labels:
    name: secret-test
spec:
  volumes:
  - name: secret
    secret:
      secretName: mysecret
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - name: "secret"
      readOnly: true
      mountPath: "/tmp/mysec"
